AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Virtual Try-On Backend
  Serverless architecture with API Gateway, Lambda, Step Functions (Standard), and DynamoDB.
  Includes User Profile management and Google Auth support.

Parameters:
  NanoBananaApiKey:
    Type: String
    Description: "API Key for the Nano-Banana Service"
    NoEcho: true
    Default: "dummy-key"

  NanoBananaApiUrl:
    Type: String
    Description: "URL for the Nano-Banana Service"
    Default: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent"

Resources:
  # -------------------------------------------------------------------------
  # DynamoDB Tables
  # -------------------------------------------------------------------------
  TryOnJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TryOnJobs
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserProfiles
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserGenerationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserGenerations
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # -------------------------------------------------------------------------
  # API Gateway (HTTP API)
  # -------------------------------------------------------------------------
  TryOnApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*" 
        AllowMethods:
          - POST
          - GET
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization

  # -------------------------------------------------------------------------
  # EventBridge Connection (Required for Step Functions HTTP Task)
  # -------------------------------------------------------------------------
  ApiConnection:
    Type: AWS::Events::Connection
    Properties:
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: "x-goog-api-key" # Updated header name
          ApiKeyValue: !Ref NanoBananaApiKey

  # -------------------------------------------------------------------------
  # Dispatcher Lambda (Trigger)
  # -------------------------------------------------------------------------
  DispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dispatcher_lambda.dispatcher_handler
      Runtime: python3.9
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt TryOnOrchestrator.Name
        - DynamoDBCrudPolicy:
            TableName: !Ref UserProfilesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TryOnJobsTable
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref TryOnOrchestrator
          USER_TABLE_NAME: !Ref UserProfilesTable
          TABLE_NAME: !Ref TryOnJobsTable
      Events:
        ApiTrigger:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /try-on
            Method: POST

  # -------------------------------------------------------------------------
  # Profile Lambda (User Images)
  # -------------------------------------------------------------------------
  ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dispatcher_lambda.profile_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserProfilesTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserGenerationsTable
        - S3CrudPolicy:
            BucketName: !Ref TryOnBucket
      Environment:
        Variables:
          USER_TABLE_NAME: !Ref UserProfilesTable
          USER_GENERATIONS_TABLE_NAME: !Ref UserGenerationsTable
          BUCKET_NAME: !Ref TryOnBucket
      Events:
        GetUploadUrl:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /user/images/upload-url
            Method: POST
        ConfirmUpload:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /user/images
            Method: POST
        ListImages:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /user/images
            Method: GET
        ListGenerations:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /user/generations
            Method: GET
        DeleteImage:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /user/images/{fileId}
            Method: DELETE

  # -------------------------------------------------------------------------
  # Status Lambda (Polling)
  # -------------------------------------------------------------------------
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dispatcher_lambda.status_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TryOnJobsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TryOnJobsTable
      Events:
        StatusTrigger:
          Type: HttpApi
          Properties:
            ApiId: !Ref TryOnApi
            Path: /status/{jobId}
            Method: GET

  # -------------------------------------------------------------------------
  # Generator Lambda (Gemini Integration)
  # -------------------------------------------------------------------------
  GeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dispatcher_lambda.generator_handler
      Runtime: python3.9
      Timeout: 60 # Give it time to download and generate
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TryOnBucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref TryOnBucket
          GEMINI_API_KEY: !Ref NanoBananaApiKey
          GEMINI_API_URL: !Ref NanoBananaApiUrl

  # -------------------------------------------------------------------------
  # Result Saver Lambda (Worker)
  # -------------------------------------------------------------------------
  ResultSaverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dispatcher_lambda.saver_handler
      Runtime: python3.9
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TryOnBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TryOnJobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserGenerationsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TryOnJobsTable
          USER_GENERATIONS_TABLE_NAME: !Ref UserGenerationsTable
          BUCKET_NAME: !Ref TryOnBucket

  # -------------------------------------------------------------------------
  # S3 Bucket
  # -------------------------------------------------------------------------
  TryOnBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  TryOnBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TryOnBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${TryOnBucket.Arn}/*"

  # -------------------------------------------------------------------------
  # Step Function (Orchestrator)
  # -------------------------------------------------------------------------
  TryOnOrchestrator:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine.asl.json
      DefinitionSubstitutions:
        ResultSaverFunctionArn: !GetAtt ResultSaverFunction.Arn
        GeneratorFunctionArn: !GetAtt GeneratorFunction.Arn
        NanoBananaApiUrl: !Ref NanoBananaApiUrl
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ResultSaverFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GeneratorFunction

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${TryOnApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  StateMachineArn:
    Description: "Step Function ARN"
    Value: !Ref TryOnOrchestrator
