sonar.projectKey=webwardrobe-site
sonar.projectName=WebWardrobe Site
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,vite.config.ts,vitest.config.ts,.vscode/**,public/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
